version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node
      - /home/node/node_modules
