version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ./deploy/.env.prod
        MIVAR: valor
    environment:
      NODE_ENV: prod
    env_file:
      - ./deploy/.env.prod
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node
      - /home/node/node_modules
