### Crear un nuevo usuario
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
  "suscriptionState":"gratuito",
  "phone":4149869793
}

### Iniciar Sesión 
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "phone":"4142930031"
}


### Encontrar un usuario en particular
GET http://localhost:3000/api/user/3b29272f-cf0b-4e66-b9f9-cb6b6c53db02

