### Crear un nuevo usuario
POST http://localhost:3000/api/auth/validate_operator
content-type: application/json

{
  "phonesNumber":"4242250609"
}


### Iniciar Sesión 
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "phonesNumber":"4242250605"
}


### Encontrar un usuario en particular
GET http://localhost:3000/api/user/1eedbc70-479a-422d-b86d-426370f39074

