name: Deploy to Heroku

on:
  push:
    branches:
      - main # Asegúrate de ajustar esto si trabajas en otra rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Container registry
      run: |
        heroku container:login

    - name: Build and push to Heroku Container registry
      run: |
        heroku container:push web --app nombre-de-tu-aplicacion
        heroku container:release web --app nombre-de-tu-aplicacion

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
